// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOVV_7sF9p0vM1k1f58Du-x9-PlP5YzpU',
    appId: '1:552264685697:web:c380bad656a68307d2d580',
    messagingSenderId: '552264685697',
    projectId: 'volkhov-map',
    authDomain: 'volkhov-map.firebaseapp.com',
    storageBucket: 'volkhov-map.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPfj25Fd3CO9Z8VKRqBI0uzokt4u4J4Xo',
    appId: '1:552264685697:android:4eff4738b6c3c07cd2d580',
    messagingSenderId: '552264685697',
    projectId: 'volkhov-map',
    storageBucket: 'volkhov-map.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs6nOnzprsyKxQzNS1eUr5YyBd8hkjrlo',
    appId: '1:552264685697:ios:70378c9d77904d84d2d580',
    messagingSenderId: '552264685697',
    projectId: 'volkhov-map',
    storageBucket: 'volkhov-map.appspot.com',
    iosClientId: '552264685697-jf5hc4g2ul7jj1581v5d7blv2o08ovmb.apps.googleusercontent.com',
    iosBundleId: 'com.extrawest.providerStarterApp',
  );
}
